name: Validate Examples

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  verify-file-schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: { submodules: recursive }
      - name: create file in data
        shell: bash -l {0}
        run: |
          cd data
          touch foo.txt
          ls
      - name: verify that the file is there
        shell: bash -l {0}
        run: |
            ls
